version: "3.7"

services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 21392996
      POSTGRES_USER: risqlac
      POSTGRES_DB: risqlacdb
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - .:/usr/server/app
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
